artifacts_root: artifacts

data_injection:
    root_dir : artifacts/data_injection
    source_url : https://github.com/sarath84/datasetrepo/raw/refs/heads/main/wine_quality.zip
    local_data_file : artifacts/data_injection/data.zip
    unzip_path      : artifacts/data_injection